### ISSUE TITLE
404 and 500 errors from Jenkins are lost

### ISSUE THREAD

**Issue by ceralena** [yosida95/golang-jenkins#2]
When calling `GetBuild()`, the error returned can be this:

```
invalid character '<' looking for beginning of value
```

This is an error from the `encoding/json` package produced when trying to decode the response to `/job/name/number`. If the job doesn't exist, the 404 response from Jenkins unfortunately has a HTML body, not a JSON body.

I'd like to change the code so that this error is caught by checking the response body and replacing it with something like `ErrJobNotFound`, so that my calling code can handle this more cleanly.

This actually happens quite often, as I often try to submit a job then immediately get its status, and Jenkins sends a 404 when the job is still queued.

The code for this is trivial, but I thought I'd put this in as an issue to get any feedback before I put in a PR.

**Comment by Karl-Gustav** [comment]
Is there a reason this hasn't been implemented? Still getting the `invalid character` error :-(

**Comment by Karl-Gustav** [comment]
Is there a reason this hasn't been implemented yet? I'm still getting the `invalid character` error :-(

**Comment by icholy** [comment]
Fixed in #56

**Comment by yosida95** [comment]
Sorry for the late response. This issue is now fixed in #56 (Thanks @icholy ) .
