### ISSUE TITLE
Requests can't be parallelized

### ISSUE THREAD

**Issue by JaredReisinger** [yosida95/golang-jenkins#33]
At present, a `Jenkins` object has a single `Requester`, and context (headers, "api/json" suffix, etc.) is cached in the singleton `Requester` for the duration of a request/response.  This means that any kind of data mining (getting the SCM data for each job, say) must be done one-at-a-time.

I'm working on a fix for this (over in https://github.com/JaredReisinger/gojenkins), by moving the per-request contextual data into a `Request` object which gets created for _each_ request.  In doing so, there is a lot less utility in the `Requester` class... its functionality could be pushed back up into the `Jenkins` object.  My plan of record, however, is to leave the minimal `Requester` type so that other dependent code doesn't break.

**Comment by JaredReisinger** [comment]
I decided to try a different approach, closing this issue (since it doesn't matter to me as much any more).

**Comment by vitalyisaev2** [comment]
Another client library suffers from same problem (https://github.com/bndr/gojenkins/issues/35)...
